export default {
  windowEl: window,
  documentEl: document,
  htmlEl: document.documentElement,
  bodyEl: document.body,
}

const CATALOG = [
  {
    id: 'sofa-t-75',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.9',
    name: 'Диван апартековый',
    model: 'T-75',
    price: '64 990',
    similar: [],
  },
  {
    id: 'sofa-d-31',
    category: 'sofa',
    subcategory: 'straight-sofa',
    subcategoryLbl: 'прямой',
    raiting: '4.8',
    name: 'Диван тканевый',
    descr: 'Мини 120 см без ящика Stark синий (Рогожка)',
    model: 'D-31',
    price: '28 490',
    img: 5,
    parameters: [
      {name: 'Гарантия', value: '18 месяцев'},
      {name: 'Артикул', value: 'AAA41269004'},
      {name: 'Длина', value: '163 см'},
      {name: 'Высота', value: '90 см'},
      {name: 'Глубина', value: '108 см'},
      {name: 'Спальное место', value: '200 см х 125 см'},
      {name: 'Высота посадки', value: '45 см'},
      {name: 'Механизм', value: 'Опорный'},
      {name: 'Тип обивки', value: 'Рогожка'},
      {name: 'Цвет', value: 'Синий'},
      {name: 'Наполнитель', value: 'Независимый пружинный блок'},
      {name: 'Материал каркаса', value: 'Металл. рама с дерев. латами'},
      {name: 'Количество мест', value: 'Двухместные'},
      {name: 'Категория', value: 'Прямые тканевые диваны'},
      {name: 'Возврат', value: 'Условия'},
    ],
    similar: ['sofa-r-85', 'sofa-h-58', 'sofa-s-44', 'sofa-v-43', 'sofa-c-42', 'sofa-f-41'],
  },
  {
    id: 'sofa-y-68',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.8',
    name: 'Диван велюровый',
    model: 'Y-68',
    price: '22 990',
    similar: [],
  },
  {
    id: 'sofa-w-95',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.8',
    name: 'Диван из шинила',
    model: 'W-95',
    price: '22 990',
    similar: [],
  },
  {
    id: 'sofa-r-94',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '5.0',
    name: 'Диван кожаный',
    model: 'R-94',
    price: '94 990',
    similar: [],
  },
  {
    id: 'sofa-g-41',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.8',
    name: 'Диван флоковый',
    model: 'G-41',
    price: '17 990',
    similar: [],
  },
  {
    id: 'sofa-c-80',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.4',
    name: 'Диван из шинила',
    model: 'C-80',
    price: '20 990',
    similar: [],
  },
  {
    id: 'sofa-v-43',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.8',
    name: 'Диван шиниловый',
    model: 'V-43',
    price: '19 990',
    similar: [],
  },
  {
    id: 'sofa-s-99',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.7',
    name: 'Диван велюровый',
    model: 'S-99',
    price: '19 990',
    similar: [],
  },
  {
    id: 'sofa-f-85',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.7',
    name: 'Диван из кожзама',
    model: 'F-85',
    price: '26 990',
    similar: [],
  },
  {
    id: 'sofa-h-64',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.6',
    name: 'Диван флоковый',
    model: 'H-64',
    price: '25 990',
    similar: [],
  },
  {
    id: 'sofa-h-58',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.6',
    name: 'Диван флоковый',
    model: 'H-58',
    price: '23 990',
    similar: [],
  },
  {
    id: 'sofa-r-43',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.6',
    name: 'Диван из кожзама',
    model: 'R-43',
    price: '33 990',
    similar: [],
  },
  {
    id: 'sofa-c-42',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.6',
    name: 'Диван из шинила',
    model: 'C-42',
    price: '18 990',
    similar: [],
  },
  {
    id: 'sofa-u-58',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.6',
    name: 'Диван велюровый',
    model: 'U-58',
    price: '21 990',
    similar: [],
  },
  {
    id: 'sofa-f-41',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.5',
    name: 'Диван флоковый',
    model: 'S-99',
    price: '19 990',
    similar: [],
  },
  {
    id: 'sofa-r-85',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.5',
    name: 'Диван велюровый',
    model: 'R-85',
    price: '34 990',
    similar: [],
  },
  {
    id: 'sofa-s-44',
    category: 'sofa',
    subcategory: 'straight-sofa',
    raiting: '4.5',
    name: 'Диван велюровый',
    model: 'S-44',
    price: '19 990',
    similar: [],
  },
];

const CATEGORIES = [
  {
    category: 'sofa',
    subcategories: [
      {
        subcategory: 'straight-sofa',
        descr: '<span>Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.</span> <span>Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.</>',
        img: 2,
        alt: 'схема дивана',
      }
    ]
  }
];

window.CATALOG = CATALOG;
window.CATEGORIES = CATEGORIES;
